spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:meeting
    username: sa
    password: sa
  jpa:
    open-in-view: false
    properties:
      hibernate:
        show_sql: true
        globally_quoted_identifiers: true
  h2:
    console:
      enabled: true